config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq"
  mount Crono::Web, at: "/crono"

  root to: "articles#index"

  namespace 'admin' do
    root to: "articles#new"
    post "/", to: "articles#update"
    patch "/", to: "articles#update"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Broadcast

  scope :from_yandex, -> { where published_to: nil }
  scope :with_actual_published_to, -> { where("published_to > ?", Time.zone.now) }

  validates :title, presence: true
  validates :annotation, presence: true
  validate :check_published_to, on: [:create, :update], if: -> { self.published_to.present? }

  def check_published_to
    if published_to < DateTime.now
      errors.add(:published_to, "can't be in the past")
    end
  end

  class << self
    def actual
      actual_from_author || actual_from_yandex
    end

    def actual_from_author
      with_actual_published_to.last
    end

    def actual_from_yandex
      from_yandex.last
    end
  end
end

app/models/concerns/broadcast.rb
module Broadcast
  extend ActiveSupport::Concern

  included do
    after_commit :broadcast, on: [:create, :update], if: -> { self.eql? Article.actual }

    def broadcast
      NewsBroadcastJob.perform_later
      NewsBroadcastJob.set(wait_until: published_to + 1.seconds).perform_later if published_to
    end
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < ApplicationController
    before_action :set_article

    def new; end

    def update
      if @article.update_attributes(article_params)
        flash.now[:success] = "Successful"
      else
        flash.now[:error] = "Failed"
      end
      render :new
    end

    private

    def set_article
      @article = Article.actual_from_author || Article.new
    end

    def article_params
      params.require(:article).permit(:title, :annotation, :published_to)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.actual
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.haml
= form_for @article, url: admin_path, html: {class: "ui form"}  do |f|
  - if flash[:success].present?
    .ui.tertiary.inverted.green.segment
      .item= flash[:success]
  - if flash[:error].present?
    .ui.tertiary.inverted.red.segment
      .ui.bulleted.list
        - @article.errors&.full_messages&.each do |msg|
          .item= msg
  .field
    =f.label :title
    =f.text_field :title
  .field
    =f.label :annotation
    =f.text_area :annotation
  .field
    =f.label :published_to
    .fields
      =f.datetime_select :published_to
    %label
      ="Use timezone: #{Time.zone.name}"

  =f.submit 'Save', class: 'ui button'

app/views/admin/articles/new.html.haml
= render 'admin/articles/form'

app/views/articles/_article.html.haml
#Article
  .ui.items
    .item
      .content
        %p.header
          = article.title
        .description
          = article.annotation.html_safe
        .extra
          = (article.published_at || article.created_at).strftime("%v %H:%M (%Z)")

app/views/articles/_empty.html.haml
.header
  No news

app/views/articles/actual.html.haml
- if @article
  = render "article", article: @article
- else
  = render "empty"

app/views/articles/index.html.haml
- if @article
  = render "article", article: @article
- else
  = render "empty"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Gudex
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    .ui.borderless.main.menu
      .ui.container
        %a.ui.item{href: root_path}
          Главная страница
        %a.ui.item{href: admin_path}
          Создать новость
        %a.ui.item{href: sidekiq_web_path, target: '_blank'}
          Sidekiq
        %a.ui.item{href: crono_web_path, target: '_blank'}
          Crono
    .ui.stackable.page.grid
      .ui.wide.column
        .ui.segment
          = yield